# Snowflake config reference: https://docs.getdbt.com/reference/warehouse-profiles/snowflake-profile
#
# Warning: Do not store credentials in this file unless you've take the necessary steps to remove
# this file from your git commit.
config:
  send_anonymous_usage_stats: False
  use_colors: True
meltano:
  target: snowflake  # The default profile name if no other profile is selected.
  outputs:
    # TODO: Optionally, revise or add to these profiles to reflect your own environments.
    snowflake:
      type: snowflake
      threads: 2
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      password: "{{ env_var('DBT_SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('DBT_SNOWFLAKE_ROLE') }}"
      warehouse: "{{ env_var('DBT_SNOWFLAKE_WAREHOUSE') }}"
      database: "{{ env_var('DBT_SNOWFLAKE_DATABASE') }}"
      schema: "{{ env_var('DBT_SNOWFLAKE_SCHEMA') }}"
